### ISSUE TITLE
Install fails regardless of install method

### ISSUE THREAD

**Issue by jtabox** [plugget/plugget-blender-addon#7]
Hey. I've been trying to install plugget in every available way but it's been throwing exceptions and failing.

I've tried multiple times, both opening the .blend file for auto-install, and the manual installation but both fail.

This is the console output when trying to install via opening the recommended .blend file:

```
Read blend: "C:\Temp\MicrosoftEdgeDownloads\d19fb86e-1001-4894-81ce-f2de88b6a80a\install_plugget_addon.blend"
Collecting plugget
  Using cached plugget-0.1.5-py3-none-any.whl (35 kB)
Collecting py-pip
  Using cached py_pip-0.0.9-py3-none-any.whl (4.9 kB)
Collecting detect-app
  Using cached detect_app-0.0.4-py3-none-any.whl (7.9 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Installing collected packages: urllib3, py-pip, idna, detect-app, charset-normalizer, certifi, requests, plugget
Successfully installed certifi-2023.11.17 charset-normalizer-3.3.2 detect-app-0.0.4 idna-3.6 plugget-0.1.5 py-pip-0.0.9 requests-2.31.0 urllib3-2.1.0

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\bin\python.exe -m pip install --upgrade pip

settings_path C:\Users\ioann\AppData\Roaming\plugget\settings_plugget.json
Exception in module register(): C:\Users\ioann\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\plugget_addon\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\ioann\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\plugget_addon\__init__.py", line 340, in register
    _register_plugget_config()
  File "C:\Users\ioann\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\plugget_addon\__init__.py", line 34, in _register_plugget_config
    plugget.settings.registered_settings_paths.add(settings_path)
AttributeError: module 'plugget.settings' has no attribute 'registered_settings_paths'

Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\ioann\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\plugget_addon\__init__.py", line 340, in register
    _register_plugget_config()
  File "C:\Users\ioann\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\plugget_addon\__init__.py", line 34, in _register_plugget_config
    plugget.settings.registered_settings_paths.add(settings_path)
AttributeError: module 'plugget.settings' has no attribute 'registered_settings_paths'

Error: Python: Traceback (most recent call last):
  File "C:\Temp\MicrosoftEdgeDownloads\d19fb86e-1001-4894-81ce-f2de88b6a80a\install_plugget_addon.blend\auto install Plugget Add-on", line 42, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\ioann\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\plugget_addon\__init__.py", line 340, in register
    _register_plugget_config()
  File "C:\Users\ioann\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\plugget_addon\__init__.py", line 34, in _register_plugget_config
    plugget.settings.registered_settings_paths.add(settings_path)
AttributeError: module 'plugget.settings' has no attribute 'registered_settings_paths'
```

The same exception is thrown when trying to activate the addon manually. I'm running Blender ver.3.6.7 (the latest LTS) on Windows 11 Pro.

**Comment by hannesdelbeke** [comment]
Hi, i ll have a look.

**Comment by hannesdelbeke** [comment]
it looks like plugget 1.6.0 failed to deploy to pypi. 
so the installed plugget version is outdated atm.
a workaround for now while i try fix this, would be to uninstall the plugget dependency, and install plugget from the repo https://github.com/plugget/plugget

**Comment by hannesdelbeke** [comment]
this should be fixed now.
i suggest you delete the plugget dependency in `addons/modules`
re enabling the addon should re download the latest plugget

**Comment by hannesdelbeke** [comment]
ah thanks for the breakdown. i ll address that

FYI: the non-qt plugget addon seems to load, but search is not showing anything for me in blender 4.

**Comment by hannesdelbeke** [comment]
thanks for the breakdown, i ll close this issue and opened a new one for the search bug
