### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by hannesdelbeke** [plugget/plugget-blender-addon#8]
when running install script, it looks like the addon was installed. but i get
```
ModuleNotFoundError: No module named 'plugget_addon'
```
same when i manually try to enable the addon in blender 4.0.2

when manually running the whole addon in script editor, i get
```
Collecting plugget
  Downloading plugget-0.1.6-py3-none-any.whl (36 kB)
Collecting py-pip
  Downloading py_pip-0.0.9-py3-none-any.whl (4.9 kB)
Collecting detect-app
  Downloading detect_app-0.0.4-py3-none-any.whl (7.9 kB)
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ---------------------------------------- 62.6/62.6 kB 1.7 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
     -------------------------------------- 100.3/100.3 kB 5.6 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
     -------------------------------------- 162.5/162.5 kB 4.8 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.1.0-py3-none-any.whl (104 kB)
     -------------------------------------- 104.6/104.6 kB 5.9 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.6-py3-none-any.whl (61 kB)
     ---------------------------------------- 61.6/61.6 kB 3.2 MB/s eta 0:00:00
Installing collected packages: urllib3, py-pip, idna, detect-app, charset-normalizer, certifi, requests, plugget
Successfully installed certifi-2023.11.17 charset-normalizer-3.3.2 detect-app-0.0.4 idna-3.6 plugget-0.1.6 py-pip-0.0.9 requests-2.31.0 urllib3-2.1.0

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: D:\Blender_Launcher_v1.16.1_Windows_x64\builds\stable\blender-4.0.2-windows-x64\4.0\python\bin\python.exe -m pip install --upgrade pip

WARNING:root:settings file not found: 'C:\Users\H\AppData\Roaming\plugget\settings_plugget.json'
Traceback (most recent call last):
  File "\Text", line 352, in <module>
  File "\Text", line 340, in register
  File "\Text", line 32, in _register_plugget_config
  File "D:\Blender_Launcher_v1.16.1_Windows_x64\builds\stable\blender-4.0.2-windows-x64\4.0\python\lib\importlib\resources.py", line 119, in path
    reader = _common.get_resource_reader(_common.get_package(package))
  File "D:\Blender_Launcher_v1.16.1_Windows_x64\builds\stable\blender-4.0.2-windows-x64\4.0\python\lib\importlib\_common.py", line 66, in get_package
    resolved = resolve(package)
  File "D:\Blender_Launcher_v1.16.1_Windows_x64\builds\stable\blender-4.0.2-windows-x64\4.0\python\lib\importlib\_common.py", line 57, in resolve
    return cand if isinstance(cand, types.ModuleType) else importlib.import_module(cand)
  File "D:\Blender_Launcher_v1.16.1_Windows_x64\builds\stable\blender-4.0.2-windows-x64\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugget_addon'
Error: Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plugget_addon'
```

**Comment by hannesdelbeke** [comment]
after restart, i get this on enable
```
WARNING:root:settings file not found: 'C:\Users\H\AppData\Roaming\plugget\settings_plugget.json'
Exception in module register(): C:\Users\H\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\plugget_addon\__init__.py
Traceback (most recent call last):
  File "D:\Blender_Launcher_v1.16.1_Windows_x64\builds\stable\blender-4.0.2-windows-x64\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\H\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\plugget_addon\__init__.py", line 340, in register
    _register_plugget_config()
  File "C:\Users\H\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\plugget_addon\__init__.py", line 34, in _register_plugget_config
    plugget.settings.registered_settings_paths.add(settings_path)
AttributeError: 'list' object has no attribute 'add'
```

**Comment by hannesdelbeke** [comment]
resolved the add / list. install seems to work now.

retesting still yields error
`ModuleNotFoundError: No module named 'plugget_addon'`
it will work on Blender restart however.

`importlib.invalidate_caches()` didn't prevent the error

**Comment by hannesdelbeke** [comment]
believe this might be cause the addon and modules folder dont yet exist when i installed the plugin.
tried to add manually to the path, but still the same
```python
import sys
sys.path.append(local_addons_dir)
```

**Comment by hannesdelbeke** [comment]
this works, if we start blender with an empty addons folder instead of no addons folder.
this proves this remaining bug is related to blender addon path handling, and not to plugget

**Comment by hannesdelbeke** [comment]
using `from addon_utils import enable` instead, fixes this.
